# Generated by Django 4.1.5 on 2023-01-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sthiraapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
